# Makefile for command-line+browser-based wordpress development

PORT = 8888
TARGET = work-shop


all: frontend

frontend:
	open http://localhost:$(PORT)/$(TARGET)

backend:
	open http://localhost:$(PORT)/$(TARGET)/wp-admin